name = "OpenHPLjl"
uuid = "18ddd5a2-5109-408b-90da-3f03c17517f1"
authors = ["Madhusudhan Pandey"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c4-0bf5283fa5ed"

[compat]
julia = "1.12"
ModelingToolkit = "11"
OrdinaryDiffEq = "6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
