name = "OpenHPLjl"
uuid = "63d83914-40af-4f5b-bce3-9fb1d85d646d"
authors = ["Madhusudhan Pandey"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c8-0e6c0c7a0c6a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
julia = "1.12"
ModelingToolkit = "10"
OrdinaryDiffEq = "6"
SciMLBase = "2"
