"""
    FCRTestSMIB(; name, product=:FCRDUp, test=:ramp, ...)

Reduced hydropower SMIB assembled for FCR screening.

Differences from `ReducedSMIB`:
- `InfiniteGrid` is replaced by `FrequencyTestGrid`.
- the grid-frequency trajectory is generated by either `RampFrequencySignal`
  or `SineFrequencySignal`;
- `DroopGovernor` is replaced by `FCRDroopController`.

The plant physics remain unchanged.
"""
@component function FCRTestSMIB(;
    name,
    product = :FCRDUp,
    test = :ramp,
    Hup = 120.0,
    Hdown = 20.0,
    Q0 = 10.0,
    y0 = 1.0,
    rho = 1000.0,
    g = 9.81,
    eta_t = 0.90,
    eta_g = 0.98,
    Pmax = 10.0e6,
    f0 = 50.0,
    J = 1.0e5,
    damping = 0.0,
    As = 500.0,
    L_headrace = 300.0,
    A_headrace = 10.0,
    L_penstock = 500.0,
    A_penstock = 5.0,
    gate_range = 0.15,
    Tg = 0.2,
    ramp_f_start = 49.9,
    ramp_f_end = 49.0,
    ramp_t_start = 5.0,
    ramp_time = 3.75,
    sine_center = 50.0,
    sine_amplitude = 0.1,
    sine_period = 60.0,
    sine_t_start = 5.0,
)
    test in (:ramp, :sine) || throw(ArgumentError("test must be :ramp or :sine"))

    Ht0 = Hup - Hdown
    Ht0 > 0 || throw(ArgumentError("FCRTestSMIB requires Hup > Hdown"))
    y0 > 0 || throw(ArgumentError("FCRTestSMIB requires y0 > 0"))
    Pmax > 0 || throw(ArgumentError("FCRTestSMIB requires Pmax > 0"))

    Kq0 = Q0 / (y0 * sqrt(Ht0))
    Ph0 = rho * g * eta_t * Q0 * Ht0
    Pe0 = eta_g * Ph0
    Pe0 < Pmax || throw(ArgumentError("Pmax must exceed initial electrical power"))
    delta0 = asin(Pe0 / Pmax)
    omega0 = 2 * pi * f0

    @named upstream = InfiniteReservoir(H0 = Hup)
    @named headrace = RigidPipe(
        friction = :none,
        L = L_headrace,
        A = A_headrace,
        g = g,
        Q0 = Q0,
    )
    @named surge = SurgeTank(As = As, H0 = Hup)
    @named penstock = RigidPipe(
        friction = :none,
        L = L_penstock,
        A = A_penstock,
        g = g,
        Q0 = Q0,
    )
    @named turbine = ShaftCoupledTurbine(
        rho = rho,
        g = g,
        eta = eta_t,
        Kq = Kq0,
    )
    @named tailwater = InfiniteReservoir(H0 = Hdown)

    @named shaft = LumpedShaft(
        J = J,
        damping = damping,
        omega0 = omega0,
    )
    @named generator = SMIBGenerator(
        eta = eta_g,
        Pmax = Pmax,
        delta0 = delta0,
    )
    @named grid = FrequencyTestGrid()
    @named frequency_sensor = FrequencySensor()
    @named controller = FCRDroopController(
        product = product,
        f0 = f0,
        y0 = y0,
        gate_range = gate_range,
        Tg = Tg,
    )

    source = if test == :ramp
        RampFrequencySignal(
            name = :frequency_source,
            f_start = ramp_f_start,
            f_end = ramp_f_end,
            t_start = ramp_t_start,
            ramp_time = ramp_time,
        )
    else
        SineFrequencySignal(
            name = :frequency_source,
            f_center = sine_center,
            amplitude = sine_amplitude,
            period = sine_period,
            t_start = sine_t_start,
        )
    end

    eqs = [
        connect(upstream.port, headrace.inlet)
        connect(headrace.outlet, surge.inlet)
        connect(surge.outlet, penstock.inlet)
        connect(penstock.outlet, turbine.inlet)
        connect(turbine.outlet, tailwater.port)
        connect(turbine.shaft, shaft.drive)
        connect(shaft.load, generator.shaft, frequency_sensor.port)
        connect(generator.grid, grid.port)
        connect(source.y, grid.f_cmd)
        connect(frequency_sensor.y, controller.f_meas)
        connect(controller.gate, turbine.gate)
    ]

    systems = [
        upstream,
        headrace,
        surge,
        penstock,
        turbine,
        tailwater,
        shaft,
        generator,
        grid,
        frequency_sensor,
        controller,
        source,
    ]

    return System(eqs, t; systems = systems, name = name)
end
